# team/state.py
from typing import TypedDict, List, Optional
class TeamState(TypedDict):
    """
    Represents the shared state of the AI development team.
    """
    # The initial high-level task from the user
    task: str
    
    # The detailed plan created by the Architect
    plan: str
    
    # The code generated by the Coder
    code: str
    
    # The file path for the generated code
    code_file_path: str
    
    # The results from the Tester
    test_results: str
    
    # The review comments from the Code Reviewer
    review_comments: str
    
    # A log of actions taken by the team to show progress
    agent_log: List[str]